version: '3.8'

services:
  apiserver:
    image: check-in-timer:latest
    # entrypoint: "/bin/bash"
    entrypoint: "python3 -m flask --debug run --host=0.0.0.0"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - /c/Users/dvisb/linux/check-in-timer:/check-in-timer
