version: '3.8'

services:
  apiserver:
    image: python-docker:latest
    # entrypoint: "/bin/bash"
    entrypoint: "python3 -m flask --debug run --host=0.0.0.0"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - /c/Users/dvisb/linux/flask-api-server:/python-docker
